##################################################
###### Dockerfile for Unitree Robot-GO2 ROS2
##################################################
FROM osrf/ros:foxy-desktop
LABEL maintainer="gogojjh <jiaojh1994@gmail.com>"

############### Path Parameters
ENV XDG_RUNTIME_DIR=/tmp/runtime-root
RUN mkdir -p $XDG_RUNTIME_DIR && chmod 700 $XDG_RUNTIME_DIR

############### Basic Ubuntu command
# TZData goes first.
RUN apt-get update
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get -y install tzdata

RUN mkdir -p /usr/app
RUN apt-get update && apt-get install -y \
  libatlas-base-dev \
  libeigen3-dev \
  libgoogle-glog-dev \
  libsuitesparse-dev \
  libtool \
  libgtest-dev \
  curl \
  libsqlite3-dev \
  ssh \
  git \
  jq \
  gnupg \
  apt-utils \
  software-properties-common \
  build-essential \
  nfs-common \
  locate \
  vim \
  git \
  gdb \
  htop
RUN apt install -y cmake 

# Unitree ROS2 package
ENV ROS_DISTRO=foxy
RUN apt install -y \
  ros-${ROS_DISTRO}-rmw-cyclonedds-cpp \
  ros-${ROS_DISTRO}-rosidl-generator-dds-idl \
  ros-${ROS_DISTRO}-gazebo-ros2-control \
  ros-${ROS_DISTRO}-xacro \
  ros-${ROS_DISTRO}-robot-localization \
  ros-${ROS_DISTRO}-ros2-controllers \
  ros-${ROS_DISTRO}-ros2-control \
  ros-${ROS_DISTRO}-velodyne \
  ros-${ROS_DISTRO}-velodyne-gazebo-plugins \
  ros-${ROS_DISTRO}-velodyne-description  

RUN apt install -y \
  python3-rosdep \
  python3-rosinstall \
  python3-rosinstall-generator \
  python3-wstool \
  build-essential \
  python3-rosdep \
  python3-pip \
  python3-setuptools

############### SLAM-related packages
RUN apt-get update && apt-get install -y \
  ros-${ROS_DISTRO}-pcl-ros \
  ros-${ROS_DISTRO}-tf-conversions \
  ros-${ROS_DISTRO}-eigen-conversions \
  ros-${ROS_DISTRO}-image-geometry \
  ros-${ROS_DISTRO}-camera-info-manager \
  ros-${ROS_DISTRO}-image-view \
  ros-${ROS_DISTRO}-cv-bridge \
  ros-${ROS_DISTRO}-tf \
  ros-${ROS_DISTRO}-tf2 \
  ros-${ROS_DISTRO}-tf2-eigen \
  ros-${ROS_DISTRO}-tf2-ros \
  ros-${ROS_DISTRO}-message-filters \
  ros-${ROS_DISTRO}-image-transport \
  ros-${ROS_DISTRO}-image-transport* \
  ros-${ROS_DISTRO}-roscpp-tutorials \
  ros-${ROS_DISTRO}-gazebo-* 

# Install Python apt dependencies
RUN apt-get install --no-install-recommends -y \
  python3 \
  python3-numpy \
  python3-pip \
  python3-vcstool \
  && rm -rf /var/lib/apt/lists/*