##################################################
###### Dockerfile for Unitree Robot-GO2 ROS2
##################################################
FROM osrf/ros:humble-desktop-full
LABEL maintainer="gogojjh <jiaojh1994@gmail.com>"

############### Path Parameters
ENV XDG_RUNTIME_DIR=/tmp/runtime-root
RUN mkdir -p $XDG_RUNTIME_DIR && chmod 700 $XDG_RUNTIME_DIR

############### Basic Ubuntu command
# TZData goes first.
RUN apt-get update
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get -y install tzdata

RUN mkdir -p /usr/app
RUN apt-get update 
RUN apt install -y cmake 

# Unitree ROS2 package
ENV ROS_DISTRO=humble
RUN apt install -y \
  ros-${ROS_DISTRO}-joy \
  ros-${ROS_DISTRO}-gazebo-* \
  ros-${ROS_DISTRO}-image-* \
  python3-colcon-common-extensions

# RUN apt install -y \
#   python3-rosdep \
#   python3-rosinstall \
#   python3-rosinstall-generator \
#   python3-wstool \
#   build-essential \
#   python3-pip \
#   python3-setuptools
# RUN rosdep update

# Install Python apt dependencies
# RUN apt-get install --no-install-recommends -y \
#   python3 \
#   python3-numpy \
#   python3-pip \
#   python3-vcstool \
#   && rm -rf /var/lib/apt/lists/*